name: Update Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: SIPT  # 👈 Ensure npm runs inside the SIPT folder

      - name: Run build
        run: npm run build
        working-directory: SIPT  # 👈 Ensure build runs inside the SIPT folder

      - name: Deploy
        run: npm run deploy
        working-directory: SIPT  # 👈 Ensure deploy runs inside the SIPT folder
