name: Update M3U File

on:
  schedule:
    - cron: "*/3 * * * *" # Runs every 3 minutes
  push:
    branches:
      - main

concurrency:
  group: update-m3u
  cancel-in-progress: true

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Increase timeout to 10 minutes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear cache
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npm exec playwright install

      - name: Verify Playwright installation
        run: npx playwright --version

      - name: Run scraper
        run: node scraper.js

      - name: Commit and push updated M3U file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/bigbrother.m3u
          git status
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated M3U file"
            git push
          fi