name: Update M3U File

on:
  schedule:
    - cron: "*/3 * * * *" # Runs every 3 minutes
  push:
    branches:
      - main

concurrency:
  group: update-m3u
  cancel-in-progress: true

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run scraper
        run: node scraper.js

      - name: Commit and push updated M3U file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/bigbrother.m3u
          git diff --quiet && git diff --cached --quiet || (git commit -m "Updated M3U file" && git push)